# Generated by Django 4.1.6 on 2023-06-13 10:35

import common.utils.mime_validator
import common.utils.upload_path
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("cover", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=55)),
                ("picture", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=35)),
                (
                    "song_file",
                    models.FileField(
                        upload_to=common.utils.upload_path.file_upload_path,
                        validators=[
                            common.utils.mime_validator.FileMimeValidator("AUDIO")
                        ],
                    ),
                ),
                ("content_type", models.CharField(max_length=50)),
                ("lyrics", models.TextField(blank=True)),
                (
                    "s_album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.album"
                    ),
                ),
                (
                    "s_artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.artist"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="music.artist"
            ),
        ),
    ]
