# Generated by Django 4.1.6 on 2023-04-14 18:28

import common.utils.mime_validator
import common.utils.upload_path
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudioPodcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('number_of_episodes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(to='studio.genre')),
            ],
        ),
        migrations.CreateModel(
            name='StudioEpisode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to=common.utils.upload_path.file_upload_path, validators=[common.utils.mime_validator.FileMimeValidator('AUDIO')])),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.studiopodcast')),
            ],
        ),
    ]
