# Generated by Django 4.1.6 on 2023-04-28 18:44

import common.utils.mime_validator
import common.utils.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_alter_studioepisode_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studioepisode',
            name='file',
            field=models.FileField(upload_to=common.utils.upload_path.file_upload_path, validators=[common.utils.mime_validator.FileMimeValidator('AUDIO')]),
        ),
    ]
