# Generated by Django 4.1.6 on 2023-04-28 18:56

import common.utils.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_alter_studioepisode_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studioepisode',
            name='file',
            field=models.FileField(upload_to=common.utils.upload_path.file_upload_path),
        ),
    ]
