# Generated by Django 4.1.6 on 2023-04-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_alter_genre_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studiopodcast',
            name='genre',
        ),
        migrations.AddField(
            model_name='studiopodcast',
            name='genre',
            field=models.TextField(default='genre'),
            preserve_default=False,
        ),
    ]
