# Generated by Django 4.1.6 on 2023-04-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_remove_studiopodcast_genre_studiopodcast_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioepisode',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='studiopodcast',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
