# Generated by Django 4.1.6 on 2023-04-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_studioepisode_slug_studiopodcast_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioepisode',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studioepisode',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
