# Generated by Django 4.1.6 on 2023-04-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_studioepisode_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studioepisode',
            name='index',
            field=models.IntegerField(blank=True),
        ),
    ]
