# Generated by Django 4.1.6 on 2023-04-10 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodeUrl', models.URLField()),
                ('podcastUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast_id', models.CharField(max_length=200)),
                ('podcastUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PodcastProvider',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PodcastSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episodes_listened', models.IntegerField()),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.podcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='podcast',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.podcastprovider'),
        ),
        migrations.AddConstraint(
            model_name='podcast',
            constraint=models.UniqueConstraint(fields=('id', 'provider'), name='unique_podcast'),
        ),
    ]
